import "../Styles/Home.scss";
import "../Styles/Features.scss";
import "../Styles/Products.scss";
import "../Styles/SignUp.scss";
import "../Styles/Footer.scss";
import "../Styles/Header.scss";
import "../Styles/Shop.scss";
import "../Styles/Blog.scss";
import "../Styles/About.scss";
import "../Styles/Contact.scss";
import "../Styles/Cart.scss";
import "../Styles/Nextbtn.scss";
import "../Styles/Registration.scss";
import "../Styles/ProductDetails.scss";
import "../Styles/Profile.scss";
import "../Styles/Loading.scss";
import "../Styles/Search.scss";
import "../Styles/icon.scss";
import "../Styles/NotFound.scss";
import "../Styles/ImageSlider.scss";
import "../style.css"

export { default as About } from "./About";
export { default as Cart } from "./Cart";
export { default as Shop } from "./Shop";
export { default as Header } from "../Componants/component/Header";
export { default as Blog } from "./Blog";
export { default as Registration } from "../Componants/component/Registration";
export { default as Login } from "./Login";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as Profile } from "./Profile";
export { default as ProductDetails } from "./ProductDetails";
export { default as PrivateComponent } from "../Componants/component/PrivateComponent";
export { default as HomeLayout } from "../Componants/component/HomeLayout";
export { default as Error } from "../Pages/Error";
