// const url ="https://railwayecommerce-production.up.railway.app/"
// const url ="https://shopwithjoy.onrender.com/"
// const url ="http://localhost:3000/" 
const url ="https://4nx6ku2ceb.ap-south-1.awsapprunner.com/" 
const id = localStorage.getItem("user");
export const carturl = url+"cart"
export const getCartUrl = url+"cart/"+id
export const producturl = url+"product"
export const allcarturl = url+"allcart"
export const usersurl = url+"register"
export const login = url+"login"
export const postMessageUrl = url+"message"
export const CommentUrl = url+"comment"
export const cartCount = url+"cartcount"
export const logout = url+"logout" 
export const currentUser = url+"current-user" 
export const updateUser = url+"users/"+id
